name: Monitoreo de Páginas Web

on:
  schedule:
    - cron: "*/5 * * * *"  # Ejecutar cada 5 minutos
  workflow_dispatch:  # Permite ejecución manual

jobs:
  check_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python y caché
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'  # Habilita caché de pip automáticamente

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar el script de monitoreo
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python monitor.py
